### ISSUE TITLE
v1.1.0 unit test TestRandomFrame failed on debian buildd

### ISSUE THREAD

**Issue by rogers0** [xtaci/smux#41]
v1.1.0 unit test TestRandomFrame failed on debian buildd
- https://buildd.debian.org/status/fetch.php?pkg=golang-github-xtaci-smux&arch=all&ver=1.1.0%2Bds-1&stamp=1547086879&raw=0
```
=== RUN   TestRandomFrame
panic: Fail in goroutine after TestReadStreamAfterSessionClose has completed

goroutine 2341 [running]:
testing.(*common).Fail(0xc00469c200)
	/usr/lib/go-1.11/src/testing/testing.go:546 +0x135
testing.(*common).Error(0xc00469c200, 0xc002d80280, 0x1, 0x1)
	/usr/lib/go-1.11/src/testing/testing.go:616 +0x6f
github.com/xtaci/smux.setupServer.func1(0x5d59c0, 0xc0041be080, 0x5d6b80, 0xc00469c200)
	/<<BUILDDIR>>/golang-github-xtaci-smux-1.1.0+ds/obj-x86_64-linux-gnu/src/github.com/xtaci/smux/session_test.go:27 +0xc0
created by github.com/xtaci/smux.setupServer
	/<<BUILDDIR>>/golang-github-xtaci-smux-1.1.0+ds/obj-x86_64-linux-gnu/src/github.com/xtaci/smux/session_test.go:24 +0xb5
FAIL	github.com/xtaci/smux	5.431s
dh_auto_test: cd obj-x86_64-linux-gnu && go test -vet=off -v -p 4 github.com/xtaci/smux returned exit code 1
make: *** [debian/rules:4: build-indep] Error 1
dpkg-buildpackage: error: debian/rules build-indep subprocess returned exit status 2
```

any thought?

**Comment by xtaci** [comment]
solved?
